// data.ts
export const diabetesCards = [
	{
		icon: '/assets/v4/diet2.png',
		iconAlt: 'diet',
		iconPos: { top: 195, left: 40 },
		gradientTop: 235,
		overlayTop: 210,
		overlayTextPos: { top: 226, left: 148 },
		overlayText: 'Strict diets',
		overlaySubText: 'can be stressful.',
		bottomTextPos: { top: 306, left: 59 },
		bottomText: ['Our food plans are yummy and ', 'made just for you', '.'],
		videoSrc: '',
	},
	{
		icon: '/assets/v4/workout2.png',
		iconAlt: 'exercise',
		iconPos: { top: 402, left: 40 },
		gradientTop: 442,
		overlayTop: 417,
		overlayTextPos: { top: 433, left: 148 },
		overlayText: 'Hard workouts',
		overlaySubText: 'don’t fit your daily life?',
		bottomTextPos: { top: 513, left: 79 },
		bottomText: ["We've got simple & easy ", 'home based exercises'],
		videoSrc: '',
	},
	{
		icon: '/assets/v4/food2.png',
		iconAlt: 'food',
		iconPos: { top: 609, left: 40 },
		gradientTop: 649,
		overlayTop: 624,
		overlayTextPos: { top: 643, left: 148 },
		overlayText: 'Unsure what to eat',
		overlaySubText: 'for blood sugar?',
		bottomTextPos: { top: 720, left: 59 },
		bottomText: ['Learn to choose ', 'Healthier Food, Everyday!'],
		videoSrc: '',
	},
];
