const experts = [
	{
		id: 1,
		src: '/assets/person_1.png',
		alt: 'Dr. Amit Gupta',
		name: 'Dr. Amit Gupta',
		credentials: 'MBBS, DNB, FACE, MSc',
		quote: 'Managing diabetes requires consistency, and Tap Health makes it effortless for patients',
		experience: '10 years experience',
		achievements: ['Forbes Health Award'],
		hasLinkedIn: true,
	},
	{
		id: 2,
		src: '/assets/person_3.png',
		alt: 'Dr. Sarah Johnson',
		name: 'Dr. Yasaswini VVN',
		credentials: 'diabetes specialist',
		quote: 'Deep understanding of chronic diseases, medical knowledge, and care management processes',
		experience: '10 years experience',
		achievements: [
			'Medical Innovation Award',
			'Best Healthcare Professional 2023',
		],
		hasLinkedIn: true,
	},
	{
		id: 3,
		src: '/assets/person_2.png',
		alt: 'Prof. Michanel Che',
		name: 'Dr. Sneh P Pandey',
		credentials: 'Internal Medicine Specialist',
		quote: 'I integrate traditional care models with new AI-powered technologies to improve health outcomes.',
		experience: '10 years experience',
		achievements: ['Global Health Innovation Prize'],
		hasLinkedIn: true,
	},
	{
		id: 4,
		src: '/assets/person_1.png',
		alt: 'Dr. Amit Gupta',
		name: 'Dr. Amit Gupta',
		credentials: 'MBBS, DNB, FACE, MSc',
		quote: 'Managing diabetes requires consistency, and Tap Health makes it effortless for patients',
		experience: '10 years experience',
		achievements: ['Forbes Health Award'],
		hasLinkedIn: true,
	},
	{
		id: 5,
		src: '/assets/person_3.png',
		alt: 'Dr. Sarah Johnson',
		name: 'Dr. Yasaswini VVN',
		credentials: 'diabetes specialist',
		quote: 'Deep understanding of chronic diseases, medical knowledge, and care management processes',
		experience: '10 years experience',
		achievements: [
			'Medical Innovation Award',
			'Best Healthcare Professional 2023',
		],
		hasLinkedIn: true,
	},
	{
		id: 6,
		src: '/assets/person_2.png',
		alt: 'Prof. Michanel Che',
		name: 'Dr. Sneh P Pandey',
		credentials: 'Internal Medicine Specialist',
		quote: 'I integrate traditional care models with new AI-powered technologies to improve health outcomes.',
		experience: '10 years experience',
		achievements: ['Global Health Innovation Prize'],
		hasLinkedIn: true,
	},
];

export default experts;
